/*
 * @Author: 2FLing 349332929yaofu@gmail.com
<<<<<<< HEAD
 * @Date: 2023-04-06 17:38:17
 * @LastEditors: 2FLing 349332929yaofu@gmail.com
 * @LastEditTime: 2023-04-26 19:19:13
 * @FilePath: \discoveryChat(chat)\index.ts
=======
 * @Date: 2023-02-23 09:36:31
 * @LastEditors: 2FLing 349332929yaofu@gmail.com
 * @LastEditTime: 2023-04-13 17:33:30
 * @FilePath: \discoverChat\index.js
>>>>>>> d8e83b038d42dd6c4c51a9c49b48ca21b3e566e7
 * @Description: 这是默认设置,请设置`customMade`, 打开koroFileHeader查看配置 进行设置: https://github.com/OBKoro1/koro1FileHeader/wiki/%E9%85%8D%E7%BD%AE
 */
/*
 * ......................................&&.........................
 * ....................................&&&..........................
 * .................................&&&&............................
 * ...............................&&&&..............................
 * .............................&&&&&&..............................
 * ...........................&&&&&&....&&&..&&&&&&&&&&&&&&&........
 * ..................&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&..............
 * ................&...&&&&&&&&&&&&&&&&&&&&&&&&&&&&.................
 * .......................&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&.........
 * ...................&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...............
 * ..................&&&   &&&&&&&&&&&&&&&&&&&&&&&&&&&&&............
 * ...............&&&&&@  &&&&&&&&&&..&&&&&&&&&&&&&&&&&&&...........
 * ..............&&&&&&&&&&&&&&&.&&....&&&&&&&&&&&&&..&&&&&.........
 * ..........&&&&&&&&&&&&&&&&&&...&.....&&&&&&&&&&&&&...&&&&........
 * ........&&&&&&&&&&&&&&&&&&&.........&&&&&&&&&&&&&&&....&&&.......
 * .......&&&&&&&&.....................&&&&&&&&&&&&&&&&.....&&......
 * ........&&&&&.....................&&&&&&&&&&&&&&&&&&.............
 * ..........&...................&&&&&&&&&&&&&&&&&&&&&&&............
 * ................&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&............
 * ..................&&&&&&&&&&&&&&&&&&&&&&&&&&&&..&&&&&............
 * ..............&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&....&&&&&............
 * ...........&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&......&&&&............
 * .........&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&.........&&&&............
 * .......&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...........&&&&............
 * ......&&&&&&&&&&&&&&&&&&&...&&&&&&...............&&&.............
 * .....&&&&&&&&&&&&&&&&............................&&..............
 * ....&&&&&&&&&&&&&&&.................&&...........................
 * ...&&&&&&&&&&&&&&&.....................&&&&......................
 * ...&&&&&&&&&&.&&&........................&&&&&...................
 * ..&&&&&&&&&&&..&&..........................&&&&&&&...............
 * ..&&&&&&&&&&&&...&............&&&.....&&&&...&&&&&&&.............
 * ..&&&&&&&&&&&&&.................&&&.....&&&&&&&&&&&&&&...........
 * ..&&&&&&&&&&&&&&&&..............&&&&&&&&&&&&&&&&&&&&&&&&.........
 * ..&&.&&&&&&&&&&&&&&&&&.........&&&&&&&&&&&&&&&&&&&&&&&&&&&.......
 * ...&&..&&&&&&&&&&&&.........&&&&&&&&&&&&&&&&...&&&&&&&&&&&&......
 * ....&..&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...........&&&&&&&&.....
 * .......&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&..............&&&&&&&....
 * .......&&&&&.&&&&&&&&&&&&&&&&&&..&&&&&&&&...&..........&&&&&&....
 * ........&&&.....&&&&&&&&&&&&&.....&&&&&&&&&&...........&..&&&&...
 * .......&&&........&&&.&&&&&&&&&.....&&&&&.................&&&&...
 * .......&&&...............&&&&&&&.......&&&&&&&&............&&&...
 * ........&&...................&&&&&&.........................&&&..
 * .........&.....................&&&&........................&&....
 * ...............................&&&.......................&&......
 * ................................&&......................&&.......
 * .................................&&..............................
 * ..................................&..............................
 */

<<<<<<< HEAD
import vars from "./configs/vars.config";
import mongooseConfig from "./configs/mongoose.config";
import { globalLogger } from "./configs/logger.config";
import { app } from "./app";
import { createChannel, createConsumer, createProducer, getUserRMQ } from "./services/userMq.service";
import { ConsumeMessage } from "amqplib";
import { Channel } from "amqp-connection-manager";

const discoverChannel =  createChannel(vars.rabbitMq.disCoverRMQKey!);
const userChannel = createChannel(vars.rabbitMq.userRMQKey!);
setInterval(async () => {
  await createConsumer(discoverChannel,"1291oiewiolkd9283.discover", async (msg: ConsumeMessage, channelWrapper: Channel) => {
    if (msg.content.toString()) {
      const data = await getUserRMQ(msg.content.toString());
      channelWrapper.ack(msg);
      await createProducer(userChannel,"209i13q0iewodjwqaikmd.user", data!);
    }
  });
}, 1000);

const PORT = vars.server.Port || 3000;
=======
import express from "express";
import bodyParser from "body-parser";
import cors from "cors";
import vars from './configs/vars.config';
import mongooseConfig from "./configs/mongoose.config";
import { toolsRouter } from "./routers/tool.router";
import { chatRoomRouter } from "./routers/chatRoomRouter.router";
import { chatGroupRouter } from "./routers/chatGroup.router";
import { chatListRouter } from "./routers/chatList.router.";
import { discoverRouter } from "./routers/discover.router";
import { globalLogger } from "./configs/logger.config";
import { APIError, errorHandler } from "./middlewares/error.middleware";
import { createConsumer, createProducer } from "./services/chatMq.service";

const app = express();
app.use(cors());
app.use(bodyParser.urlencoded({
    extended: true
  }));
app.use(bodyParser.json());
app.use("/room", chatRoomRouter);
app.use("/tools", toolsRouter);
app.use('/group',chatGroupRouter);
app.use('/chatList',chatListRouter);
app.use('/discover',discoverRouter);
const PORT = vars.serverPort || 3000;
app.use(express.json());
app.use((req,res,next)=>{
  const error = new APIError(404,'Invalid source path.');
  globalLogger.error(error);
})
app.use(errorHandler);
>>>>>>> d8e83b038d42dd6c4c51a9c49b48ca21b3e566e7

mongooseConfig(vars.mongoUrl)
  .then(() => {
    app.listen(PORT, () => console.log(`Listening on port ${PORT}`));
  })
  .catch((err) => {
    globalLogger.error(err);
<<<<<<< HEAD
    console.log({ err });
  });
=======
    console.log({err});
  });
>>>>>>> d8e83b038d42dd6c4c51a9c49b48ca21b3e566e7
